-require: rubocop-rails
AllCops:
  Excludes:
    - Rakefile
    - bin/**/*
    - db/**/*
    - config/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
